- name: Install httpd for Centos
  yum:
    name: httpd
    state: latest
  notify: restart_httpd


- name: Create file with content
  copy:
    content:
      Welcome to my web server
    dest: "{{ index_path }}"


- name: Open port on firewalld
  firewalld:
    port: "{{ firewall_port }}"
    permanent: true
    state: enabled