---
- name: Include appropriate tasks for OS family and version
  include_tasks: "{{ os_specific_tasks }}"
  with_first_found:
    - "{{ ansible_distribution|lower|replace(' ', '_') }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower|replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower|replace(' ', '_') }}.yml"
    - "{{ ansible_os_family|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - "default.yml"
  loop_control:
    loop_var: os_specific_tasks


