- name: Install httpd for RedHat
  yum:
    name: httpd
    state: latest


- name: Start and enable httpd
  service:
    name: httpd
    state: restarted
    enabled: yes


- name: Create file with content
  copy:
    content:
      Welcome to my web server
    dest: "{{ index_path }}"


- name: Start and enable firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes


- name: Open port on firewalld
  firewalld:
    port: "{{ firewall_port }}"
    permanent: true
    state: enabled
  notify: restart_firewalld
