- name: Install vsftpd for RedHat
  yum:
    name: vsftpd
    state: latest


- name: Start and enable vsftpd
  service:
    name: vsftpd
    state: started
    enabled: yes


- name: Get service facts
  service_facts:


- name: Install semanage if not installed
  yum:
    name: policycoreutils
    state: latest
  when: ansible_facts.services["semanage.service"] is not defined


- name: Set ftpd_anon_write flag on a
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes


- name: Configure ftp
  template:
    src: templates/vsftpd.conf.jinja
    dest: /etc/vsftpd.conf
  notify: restart_vsftpd


- name: Open port on firewalld
  firewalld:
    port: "{{ ftp_port }}"
    permanent: true
    state: enabled


- name: Change permission directory
  file:
    path: /var/ftp/pub
    state: directory
    recurse: yes
    owner: ftp
    mode: '0755'


