---
- hosts: dev-apavlov.spb.yadro.com

  pre_tasks:

    - name: Gather minimal facts
      setup:
        gather_subset: "!all,min"
      tags:
        - always

  tasks:
  roles:
    - role: httpd
      tags: packages

    - role: network_manager
      tags: packages
